### ISSUE TITLE
Are CORS setting currently set?

### ISSUE THREAD

**Issue by bobvanluijt** [studio-spindle/cva#54]
Regarding these lines: https://github.com/studio-spindle/cva/blob/a084d7c22c13d87da9b7e38fcbfd05101672cf4b/server/app.js#L12-L26

Why not set?

```
var whitelist = ['http://localhost:3000' : 'https://creatingvalue.co']

app.use(cors({
  origin: function (origin, callback) {
    if (whitelist.indexOf(origin) !== -1) {
      callback(null, true)
    } else {
      callback(new Error('Not allowed by CORS'))
    }
  }
}));
```

**Comment by StudioSpindle** [comment]
@bobvanluijt  Sure. But did you see the message "The CORS policy for this site does not allow access from ...."?

**Comment by StudioSpindle** [comment]
https://github.com/studio-spindle/cva/pull/56
